apiVersion: v1 
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-sp
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: agent
    port: 50000
    targetPort: 50000
