apiVersion: v1 
kind: Service
metadata:
  name: webcvalera-s
  labels:
    app: webcvalera
spec:
  selector:
    app: webcvalera
  type: LoadBalancer
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
