apiVersion: v1 
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins-sp
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - name: web
      port: 8081
      targetPort: 8080
      nodePort: 32090
    - name: agent
      port: 50001
      targetPort: 50000
      nodePort: 32060
