apiVersion: apps/v1
kind: Deployment 
metadata:
  name: autocaravaneando-d
  labels:
    app: autocaravaneando
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: autocaravaneando
  template:
    metadata:
      labels: 
        app: autocaravaneando
    spec:
      containers:
        - name: autocaravaneando
          image: usuario1507/angel-react
          envFrom:
            - configMapRef:
                name: app-env-configmap
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
